trainingInput:
  scaleTier: CUSTOM
  masterType: standard_gpu
  workerType: standard_gpu
  parameterServerType: standard
  parameterServerCount: 1
  workerCount: 2
  hyperparameters:
    maxTrials: 20
    maxParallelTrials: 10
    enableTrialEarlyStopping: False
    goal: MAXIMIZE    
    hyperparameterMetricTag: ep_ret
    params:
    - parameterName: pi_lr
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.001
      scaleType: UNIT_LOG_SCALE
    - parameterName: v_lr
      type: DOUBLE
      minValue: 0.00001
      maxValue: 0.001
      scaleType: UNIT_LOG_SCALE
    - parameterName: steps_per_episode
      type: INTEGER
      minValue: 15
      maxValue: 22
      scaleType: UNIT_LOG_SCALE
    
